github:
  owner: getsentry
  repo: chartcuterie

changelogPolicy: auto

statusProvider:
  name: github
artifactProvider:
  name: github

targets:
  - id: release
    name: docker
    source: us.gcr.io/sentryio/chartcuterie
    target: getsentry/chartcuterie
  - id: latest
    name: docker
    source: us.gcr.io/sentryio/chartcuterie
    target: getsentry/chartcuterie
    targetFormat: '{{{target}}}:latest'
  - name: npm
    access: public
