minVersion: "2.19.0"
changelog:
  policy: auto
artifactProvider:
  name: none
statusProvider:
  name: github
  config:
    contexts:
      - 'build-docker-image-arm64'
      - 'build-docker-image-amd64'
      - 'assemble-chartcuterie-image'
targets:
  - id: release
    name: docker
    source: ghcr.io/getsentry/chartcuterie
    target: ghcr.io/getsentry/chartcuterie
  - id: latest
    name: docker
    source: ghcr.io/getsentry/chartcuterie
    target: ghcr.io/getsentry/chartcuterie
    targetFormat: "{{{target}}}:latest"
  - name: npm
    access: public
  - name: github

versioning:
  policy: calver