github:
  owner: getsentry
  repo: chartcuterie

changelogPolicy: auto

statusProvider:
  name: github
artifactProvider:
  name: github

targets:
  - id: release
    name: docker
    source: us-central1-docker.pkg.dev/sentryio/chartcuterie/image
    target: getsentry/chartcuterie
  - id: latest
    name: docker
    source: us-central1-docker.pkg.dev/sentryio/chartcuterie/image
    target: getsentry/chartcuterie
    targetFormat: '{{{target}}}:latest'
  - name: npm
    access: public
  - name: github
