steps:
  - name: 'gcr.io/kaniko-project/executor:v0.23.0'
    args:
      [
        '--cache=true',
        '--build-arg',
        'SOURCE_COMMIT=$COMMIT_SHA',
        '--destination=us.gcr.io/$PROJECT_ID/chartcuterie:$COMMIT_SHA',
      ]
    timeout: 900s
  # Smoke test
  - name: 'us.gcr.io/$PROJECT_ID/chartcuterie:$COMMIT_SHA'
    args:
      - '--help'
    timeout: 60s
