steps:
  # Build the app
  - name: 'node:14'
    args: ['bash', '-c', 'yarn && yarn build']
  # Build runtime image
  - name: 'gcr.io/kaniko-project/executor:v1.5.1'
    args:
      [
        '--cache=true',
        '--use-new-run',
        '--build-arg',
        'SOURCE_COMMIT=$COMMIT_SHA',
        '--destination=us.gcr.io/$PROJECT_ID/chartcuterie:$COMMIT_SHA',
      ]
    timeout: 900s
  # Smoke test
  - name: 'us.gcr.io/$PROJECT_ID/chartcuterie:$COMMIT_SHA'
    args:
      - node
      - '/usr/src/app/lib/index.js'
      - '--help'
    timeout: 60s
