# More information on gocd-flavor YAML can be found here:
# - https://github.com/tomzo/gocd-yaml-config-plugin#pipeline
# - https://www.notion.so/sentry/GoCD-New-Service-Quickstart-6d8db7a6964049b3b0e78b8a4b52e25d
format_version: 10
pipelines:
    deploy-chartcuterie:
        environment_variables:
            GCP_PROJECT: internal-sentry
            GKE_CLUSTER: zdpwkxst
            GKE_REGION: us-central1
            GKE_CLUSTER_ZONE: b
            GKE_BASTION_ZONE: b
        group: chartcuterie
        lock_behavior: unlockWhenFinished
        materials:
            chartcuterie_repo:
                git: git@github.com:getsentry/chartcuterie.git
                shallow_clone: true
                branch: master
                destination: chartcuterie
        stages:
            - checks:
                  approval:
                      type: manual
                  fetch_materials: true
                  environment_variables:
                      # Required for checkruns.
                      GITHUB_TOKEN: "{{SECRET:[devinfra-github][token]}}"
                  jobs:
                      checks:
                          timeout: 1200
                          elastic_profile_id: chartcuterie
                          tasks:
                              - script: |
                                    /devinfra/scripts/checks/githubactions/checkruns.py \
                                    getsentry/chartcuterie \
                                    ${GO_REVISION_CHARTCUTERIE_REPO} \
                                    build
                              - script: |
                                    /devinfra/scripts/checks/googlecloud/checkcloudbuild.py \
                                    ${GO_REVISION_CHARTCUTERIE_REPO} \
                                    sentryio \
                                    "us.gcr.io/sentryio/chartcuterie"
            - deploy-canary:
                  approval:
                      type: manual
                  fetch_materials: true
                  jobs:
                      deploy:
                          timeout: 1200
                          elastic_profile_id: chartcuterie
                          tasks:
                              - script: |
                                    /devinfra/scripts/k8s/k8stunnel \
                                    && /devinfra/scripts/k8s/k8sdeploy.py \
                                    --label-selector="service=chartcuterie,env=canary" \
                                    --image="us.gcr.io/sentryio/chartcuterie:${GO_REVISION_CHARTCUTERIE_REPO}" \
                                    --container-name="chartcuterie"
            - deploy-primary:
                  approval:
                      type: manual
                  fetch_materials: true
                  jobs:
                      deploy:
                          timeout: 1200
                          elastic_profile_id: chartcuterie
                          tasks:
                              - script: |
                                    /devinfra/scripts/k8s/k8stunnel \
                                    && /devinfra/scripts/k8s/k8sdeploy.py \
                                    --label-selector="service=chartcuterie" \
                                    --image="us.gcr.io/sentryio/chartcuterie:${GO_REVISION_CHARTCUTERIE_REPO}" \
                                    --container-name="chartcuterie"
