# Ignored by docker compose, used by devservices
x-sentry-service-config:
  version: 0.1
  service_name: chartcuterie
  dependencies:
    chartcuterie:
      description: Chartcuterie offers fresh slices and dices of absolutely delectable graphs.
  modes:
    default: [chartcuterie]

services:
  chartcuterie:
    image: ghcr.io/getsentry/chartcuterie:nightly
    environment:
      CHARTCUTERIE_CONFIG: /etc/chartcuterie/config.js
      CHARTCUTERIE_CONFIG_POLLING: true
    volumes:
      - $CHARTCUTERIE_CONFIG_PATH:/etc/chartcuterie
    ports:
      - 127.0.0.1:7901:9090
    networks:
      - devservices
    extra_hosts:
      host.docker.internal: host-gateway
    labels:
      - orchestrator=devservices
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://127.0.0.1:9090/api/chartcuterie/healthcheck/live').then(r=>r.ok?0:1,()=>1).then(process.exit)"]
      interval: 5s
      timeout: 5s
      retries: 3

networks:
  devservices:
    name: devservices
    external: true
