# Ignored by docker compose, used by devservices
x-sentry-service-config:
  version: 0.1
  service_name: chartcuterie
  dependencies:
    chartcuterie:
      description: Chartcuterie offers fresh slices and dices of absolutely delectable graphs.
  modes:
    default: [chartcuterie]

services:
  chartcuterie:
    image: 'us-central1-docker.pkg.dev/sentryio/chartcuterie/image:latest'
    environment:
      CHARTCUTERIE_CONFIG: /etc/chartcuterie/config.js
      CHARTCUTERIE_CONFIG_POLLING: true
    volumes:
      - $CHARTCUTERIE_CONFIG_PATH:/etc/chartcuterie
    ports:
      - 127.0.0.1:7901:9090
    networks:
      - devservices
    extra_hosts:
      host.docker.internal: host-gateway
    labels:
      - 'orchestrator=devservices'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'docker exec sentry_chartcuterie python3 -c "import urllib.request; urllib.request.urlopen(\"http://127.0.0.1:9090/api/chartcuterie/healthcheck/live\", timeout=5)"',
        ]
      interval: 5s
      timeout: 5s
      retries: 3

networks:
  devservices:
    name: devservices
    external: true
