name: build
on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn test
      - if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: snapshot diffs
          path: tests/__image_snapshots__
      - run: yarn build
      - run: yarn pack
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.sha }}
          path: |
            ${{ github.workspace }}/*.tgz
