name: build
on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: volta-cli/action@5c175f92dea6f48441c436471e6479dbc192e194 # v4.2.1
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn test
      - if: ${{ failure() }}
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: snapshot diffs
          path: tests/__image_snapshots__
      - run: yarn build
      - run: yarn pack
      - uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: ${{ github.sha }}
          path: |
            ${{ github.workspace }}/*.tgz
