name: DockerBuild
on:
  push:
    branches:
      - '*'

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    env:
      BRANCH: ${GITHUB_REF##*/}
      SERVICE_NAME: chartcuterie
      PROJECT_ID: sentryio
      COMMIT_SHA: ${GITHUB_SHA::6}
      CLOUD_PROJECT: sentryio

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCR_SERVICE_ACCOUNT }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          gcloud auth -q
      - run: |
          gcloud auth list

      # Build docker image
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: |
          bash -c yarn && yarn build

      - name: Build and push to gcr
        run: |
          gcloud builds submit \
            --project ${{ env.PROJECT_ID }}
            --verbosity="debug"
            --tag "us.gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ env.COMMIT_SHA }}"
