name: DockerBuild
on:
  push:
    branches:
      - '*'

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    env:
      BRANCH: ${GITHUB_REF##*/}
      SERVICE_NAME: chartcuterie
      PROJECT_ID: sentryio
      COMMIT_SHA: ${GITHUB_SHA::6}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCR_SERVICE_ACCOUNT }}
#         project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          gcloud auth configure-docker -q
 
      # Build docker image
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: |
          bash -c yarn && yarn build
      - uses: RafikFarhad/push-to-gcr-github-action@v3.0.2
        with:
          registry: gcr.io
          project_id: ${{ env.PROJECT_ID }}
          image_name: ${{ env.SERVICE_NAME }}
     # Push image to Google Container Registry
      - name: Build
        run: |-
          docker push us.gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ env.COMMIT_SHA }}
